version: '3.7'

services:
  db:
    container_name: schmerling_postgres
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - net1

  app:
    container_name: schmerling_app
    environment:
      - POSTGRES_HOST=db
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - net1

  server:
    container_name: schmerling_nginx
    image: steveltn/https-portal:1.4.4
    networks:
      - net1
    links:
      - app
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'

volumes:
  db-data:

networks:
  net1:
    driver: bridge
