version: '3.7'

services:
  db:
    restart: unless-stopped
    env_file:
      - ./.env.production

  app:
    restart: unless-stopped
    image: schmerling/app:0.41
    env_file:
      - ./.env.production
    environment:
      - POSTGRES_HOST=db
      - RAILS_ENV=production
      - NODE_ENV=production

  server:
    restart: unless-stopped
    environment:
      DOMAINS: 'www.schmerling.org => schmerling.org, schmerling.org -> http://app:3000'
      PRODUCTION: 'true'
