version: '3.7'

services:
  db:
    restart: unless-stopped
    env_file:
      - ./.env.staging

  app:
    restart: unless-stopped
    image: schmerling/app:0.35
    env_file:
      - ./.env.staging
    environment:
      - POSTGRES_HOST=db
      - RAILS_ENV=production
      - NODE_ENV=production

  server:
    restart: unless-stopped
    environment:
      DOMAINS: 'test.schmerling.org -> http://app:3000'
      PRODUCTION: 'true'
