version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  db:
    container_name: schmerling_postgres
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - net1
    logging: *default-logging

  app:
    container_name: schmerling_app
    environment:
      - POSTGRES_HOST=db
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - net1
    logging: *default-logging

  server:
    container_name: schmerling_nginx
    image: steveltn/https-portal:1.4.4
    networks:
      - net1
    links:
      - app
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    environment:
      CLIENT_MAX_BODY_SIZE: '20m'
      PROXY_SEND_TIMEOUT: 30
      PROXY_READ_TIMEOUT: 30
    logging: *default-logging

volumes:
  db-data:

networks:
  net1:
    driver: bridge
